/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#3f465c",
        "surface-bright": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "on-primary-fixed": "#131b2e",
        "inverse-primary": "#bec6e0",
        "secondary-container": "#d5e3fd",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#45464d",
        "on-tertiary-container": "#497cff",
        "surface-container-low": "#f2f4f6",
        "secondary": "#515f74",
        "on-tertiary-fixed": "#00174b",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#b9c7e0",
        "surface-container-highest": "#e0e3e5",
        "surface": "#f7f9fb",
        "secondary-fixed": "#d5e3fd",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed": "#dbe1ff",
        "surface-container": "#eceef0",
        "primary-fixed-dim": "#bec6e0",
        "surface-dim": "#d8dadc",
        "tertiary-container": "#00174b",
        "error": "#ba1a1a",
        "surface-variant": "#e0e3e5",
        "surface-container-high": "#e6e8ea",
        "on-secondary-container": "#57657b",
        "surface-tint": "#565e74",
        "outline": "#76777d",
        "on-tertiary-fixed-variant": "#003ea8",
        "background": "#f7f9fb",
        "outline-variant": "#c6c6cd",
        "tertiary-fixed-dim": "#b4c5ff",
        "primary-container": "#131b2e",
        "primary": "#000000",
        "inverse-surface": "#2d3133",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485c",
        "on-primary-container": "#7c839b",
        "on-secondary-fixed": "#0d1c2f",
        "on-background": "#191c1e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "md": "16px",
        "xs": "4px",
        "xl": "32px",
        "lg": "24px",
        "gutter": "24px",
        "base": "4px",
        "container-max": "1440px",
        "sm": "8px"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
